version: "3"
services:
  xm-service:
    container_name: "xm-service"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_POSTGRES_DATABASE: "xm_db"
      APP_POSTGRES_USERNAME: "postgres"
      APP_POSTGRES_PASSWORD: "postgres"
      APP_POSTGRES_HOSTNAME: "db"
      APP_NAME: "XM"
      APP_PORT: "5000"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:xm_db
      - DATABASE_HOST:db
    ports:
      - '5432:5433'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
volumes:
  database_postgres:
    driver: local
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge